PredoxWeb/PredoxWeb/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

PredoxWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app.views import serve_image
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet

urlpatterns = [
    url(r'^devices/', FCMDeviceAuthorizedViewSet.as_view({'post':'create', 'get':'list'}), name='create_fcm_device'),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^', include('frontpage.urls')),
    url(r'^api/',include('api.urls')),
    url(r'api-token-auth/', obtain_jwt_token),
    url(r'api-token-refresh/', refresh_jwt_token),
    url(r'management/',include('management.urls')),
   # url(r'inventory/', include('inventory.urls')),
   # url(r'sop/', include('SOP.urls')),
    url(r'management/projects/', include('project_management.urls')),
    url(r'^user_images/', serve_image),
]

SOP/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', login_required(views.SOPListView.as_view())),
    url(r'^upload/$',login_required(views.SOPUploadView.as_view())),
    url(r'^download/(?P<file_id>[0-9]+)$', login_required(views.SOPDownloadView)),
    url(r'^(?P<pk>[0-9]+)$', login_required(views.SOPUpdateView.as_view())),
    url(r'^find/$', login_required(views.findSOP)),
    ]

management/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Dashboard.as_view()),
    url(r'^settings', views.SettingsUpdateView.as_view()),
    url(r'^templates/$', views.TemplateListView.as_view()),
    url(r'^templates/create/$', views.TemplateCreateView.as_view()),
    url(r'^templates/edit/(?P<pk>\d+)/$', views.TemplateUpdateView.as_view()),
    url(r'^templates/delete/(?P<pk>\d+)/$', views.TemplateDeleteView.as_view()),
    url(r'^fields/$', views.FieldListView.as_view()),
    url(r'^fields/create/$', views.FieldCreateView.as_view()),
    url(r'^fields/edit/(?P<pk>\d+)/$', views.FieldUpdateView.as_view()),
    url(r'^fields/delete/(?P<pk>\d+)/$', views.FieldDeleteView.as_view()),
    url(r'^experiments/$', views.ExperimentListView.as_view()),
    url(r'^experiments/edit/(?P<pk>\d+)/$', views.ExperimentUpdateView.as_view()),
    url(r'^experiments/delete/(?P<pk>\d+)/$', views.ExperimentDeleteView.as_view()),
    url(r'^users/$', views.UserListview.as_view()),
    url(r'^users/edit/(?P<pk>\d+)/$', views.UserUpdateView.as_view()),
    url(r'^login/$', views.ManagementLoginView.as_view()),
    url(r'^groups/$', views.UserGroupListView.as_view()),
    url(r'^groups/create/$', views.UserGroupCreateView.as_view()),
    url(r'^groups/edit/(?P<pk>\d+)/$', views.UserGroupUpdateView.as_view()),
    url(r'^groups/delete/(?P<pk>\d+)/$', views.UserGroupDeleteView.as_view()),
    ]

accounts/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager
from django.utils import timezone


# Create your models here.





class Plan(models.Model):
    """
    Available plans. if is_active is true, then it is shown on the pricing page
    and can be used to register a new company.
    """
    name = models.CharField(max_length=255)
    price = models.FloatField()
    description = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class Company(models.Model):
    """
    Stores a single company. Is used to determine owner of all data
    """
    name = models.CharField(max_length=255)
    address = models.TextField()
    phone = models.CharField(max_length=20)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    good_standing = models.BooleanField(default = True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

class Payment(models.Model):
    date_payed = models.DateTimeField(_('date payed'), default=timezone.now)
    date_next_due = models.DateTimeField(_('date next due'), default=timezone.now)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    balance = models.FloatField()



class User(AbstractBaseUser, PermissionsMixin):
    """
    Model used to store users. A user must belong to a company.

    Taken from https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#abstractbaseuser
    2017/12/04
    """
    company = models.ForeignKey(Company, on_delete=models.CASCADE)  # user gets deleted if company is deleted.
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    show_tutorial = models.BooleanField(default=True)

    # For accessing management panel
    is_admin = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)

    # for accessing admin panel
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['company']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        unique_together = (('company', 'email'))

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name
        '''
        if self.first_name or self.last_name:
            return self.first_name + ' ' + self.last_name
        else:
            return self.email

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name or self.email

    def __str__(self):
        return self.get_full_name()

    def __repr__(self):
        return self.get_full_name()


class Invite(models.Model):
    """
    Stores invite information.
    The hash is company + date + email.

    """
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    hash = models.CharField(max_length=64)  # SHA256 hash

    def validate(self):
        """
        checks if the link is still active. The link expires after 24 hours.
        Returns True if link is valid, else False.
        """
        now = datetime.datetime.now()
        diff = now - self.date
        if diff.days > 0:
            return False

        return True

management/views.py
from django.shortcuts import render, redirect
from accounts.models import User
from .forms import SettingsForm, ExperimentForm, UserChangeForm, GroupForm
from .models import Settings
from app.models import Template, Fields, Experiment, ExperimentData
from accounts.models import Company
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from app.mixins import CompanyObjectCreateMixin, CompanyObjectsMixin
from json import loads
from django.http import HttpResponse, HttpResponseRedirect
from django.db.utils import Error
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.views import View
from app.mixins import ExpFilterMixin, BaseFilterMixin, UserFilterMixin
from django.contrib.auth.models import Group
from .mixins import ManagerTestMixin


class Dashboard(ManagerTestMixin, View):
    """
    Main entry point for the management part of the website. Intially this
    should show information like last logins,and allow ease of access to other
    services that are available on the management portion of the site.
    """
    def get(self, request):
        users = User.objects.filter(company=request.user.company)
        return render(request, 'management/dashboard.html', {"users": users})


class ExperimentListView(ManagerTestMixin, ExpFilterMixin, CompanyObjectsMixin, ListView):
    """
    Lists Experiments within a company, if user has permissions to page.
    """
    model = Experiment
    template_name = "management/experiment_list.html"
    paginate_by = 20


class ExperimentUpdateView(ManagerTestMixin, CompanyObjectsMixin, UpdateView):
    """
    View for editing experiments through the management panel.
    """
    model = Experiment
    template_name = "management/experiment_update.html"
    success_url = "/management/experiments"
    # fields = ('friendly_name', 'metadata', 'tags', 'project')
    form_class = ExperimentForm

    def get_context_data(self, **kwargs):
        """
        returns ExperimentData objects of Experiment and headers for experiment
        data along with default context.
        """
        context = super().get_context_data(**kwargs)
        context["exp_data"] = ExperimentData.objects.filter(experiment=self.kwargs['pk'], company=self.request.user.company)

        # TODO: require SOME data to be added on upload.

        try:
            context["headers"] = list(context["exp_data"][0].experimentData.keys())
        except IndexError:
            context["headers"] = [' ']
            context["exp_data"] = [[' ']]

        return context

    def form_valid(self, form):
        """
        handles exp_data json experiment form.
        TODO: add data type checking for fields.
        """
        exp_data = self.request.POST.get("exp_data")

        try:
            exp_data = loads(exp_data)
        except ValueError:
            return HttpResponse("Invalid Data", status="400")

        exp_data = [x for x in exp_data if any(x.values())]
        if not exp_data:
            return HttpResponse("No experiment data found.", status="400")

        self.object = form.save()

        ExperimentData.objects.filter(experiment=self.kwargs['pk'], company=self.request.user.company).delete()

        try:
            data_objects = []
            for item in exp_data:
                data_objects.append(ExperimentData(company=self.request.user.company, experimentData=item, experiment=self.object))

            ExperimentData.objects.bulk_create(data_objects)

        except Error:  # a generic database error
            return HttpResponse(status=500)

        return redirect(self.get_success_url())


class ExperimentDeleteView(ManagerTestMixin, CompanyObjectsMixin, DeleteView):
    """
    confirms the delete request on get and deletes on post
    """
    model = Experiment
    success_url = "/management/experiments"
    template_name = "management/template_confirm_delete.html"


class SettingsUpdateView(UpdateView):
    """
    View for editing settings and company information.
    Overrides methods from mixins and parent class to accomodate the extra
    settings modelform.
    """
    fields = ('name', 'address', 'phone')
    model = Company
    template_name = "management/settings.html"
    success_url = "/management/settings"

    def get_object(self, **kwargs):
        """
        returns the request user's company.
        """
        return self.request.user.company

    def get_context_data(self, **kwargs):
        """
        creates the settings form. Will create new settings object if one
        doesn't already exist.
        """

        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
            settings = Settings.objects.get_or_create(company = self.object)
            kwargs['settings'] = SettingsForm(instance=settings[0], prefix="settings")

        return super().get_context_data(**kwargs)

    def form_valid(self, form, settings):
        """
        handles model saving for company and settings.
        """

        settings.save()
        self.object = form.save()

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, settings):
        """
        if invalid, returns both forms.
        """
        return self.render_to_response(self.get_context_data(form=form, settings=settings))

    def post(self, request):
        """
        overriden to validate two both company and settings forms.
        """
        self.object = self.get_object()

        form = self.get_form()
        settings_instance = Settings.objects.get(company=self.object)
        settings = SettingsForm(self.request.POST, prefix="settings", instance=settings_instance)

        if form.is_valid() and settings.is_valid():
            return self.form_valid(form, settings)

        else:
            return self.form_invalid(form, settings)


class TemplateListView(ManagerTestMixin, BaseFilterMixin, CompanyObjectsMixin, ListView):
    """
    Class based view for displaying a list of templates.
    """
    model = Template
    template_name = "management/template_list.html"
    paginate_by = 20

    FILTERS = {
        "name": lambda x: ("name__icontains", x[0])
    }

    ORDER_FIELDS = (
        "name",
    )



class TemplateCreateView(ManagerTestMixin, CompanyObjectCreateMixin, CompanyObjectsMixin, CreateView):
    """
    View for creating templates.
    """
    model = Template
    fields = ('name', 'fields', 'metadata')
    template_name = "management/template_form.html"
    success_url = "/management/templates"


class TemplateUpdateView(ManagerTestMixin, CompanyObjectsMixin, UpdateView):
    """
    View for editing templates.
    """
    model = Template
    fields = ('name', 'fields', 'metadata')
    template_name = "management/template_form.html"
    success_url = "/management/templates"


class TemplateDeleteView(ManagerTestMixin, CompanyObjectsMixin, DeleteView):
    """
    View for deleting template.
    """
    model = Template
    template_name = "management/template_confirm_delete.html"
    success_url = "/management/templates"


class FieldListView(ManagerTestMixin, BaseFilterMixin, CompanyObjectsMixin, ListView):
    """
    Displays a list of fields.
    """
    model = Fields
    paginate_by = 20
    template_name = "management/fields_list.html"
    FILTERS = {
        "name": lambda x: ("name__icontains", x[0]),
        "data_type" : lambda x: ("data_type", x[0])
    }

    ORDER_FIELDS = (
        "name",
        "data_type"
    )


class FieldCreateView(ManagerTestMixin, CompanyObjectCreateMixin, CompanyObjectsMixin, CreateView):
    """
    Displays a list of fields.
    """
    model = Fields
    fields = ('name', 'data_type', 'empty')
    template_name = "management/fields_form.html"
    success_url = "/management/fields"


class FieldUpdateView(ManagerTestMixin, CompanyObjectsMixin, UpdateView):
    """
    View for editing fields.
    """
    model = Fields
    fields = ('name', 'data_type', 'empty')
    template_name = "management/fields_form.html"
    success_url = "/management/fields"


class FieldDeleteView(ManagerTestMixin, CompanyObjectsMixin, DeleteView):
    """
    View for editing fields.
    """
    model = Fields
    template_name = "management/fields_confirm_delete.html"
    success_url = "/management/fields"


class UserListview(ManagerTestMixin, UserFilterMixin, CompanyObjectsMixin, ListView):
    """
    displays a list of users. Users can be found by first name, last name
    and email.
    """
    model = get_user_model()
    template_name = "management/user_list.html"
    paginate_by = 20


class UserUpdateView(ManagerTestMixin, CompanyObjectsMixin, UpdateView):
    model = get_user_model()
    template_name = "management/user_update.html"
    # fields = ("first_name", "last_name", "email", "password", "groups", "user_permissions" )
    form_class = UserChangeForm
    success_url = "/management/users"


class UserGroupListView(BaseFilterMixin, ListView):
    """
    Displays a list of user groups.
    """
    model = Group
    template_name = "management/groups_list.html"
    paginate_by = 20

    FILTERS = {
        "name": lambda x: ("name__icontains", x[0]),
        "description": lambda x: ("extra__description__icontains", x[0]),
    }

    ORDER_FIELDS = (
        "name",
    )

    def get_queryset(self):
        """
        Gets queryset of groups for specified company. Slightly different field
        so it doesn't use the CompanyObjectsMixin.
        """
        qs = super().get_queryset()
        qs = qs.filter(extra__company=self.request.user.company)

        return qs


class UserGroupCreateView(CreateView):
    """
    Displays form for creating new user group.
    """
    model = Group
    template_name = "management/groups_form.html"
    form_class = GroupForm
    success_url = '/management/groups'

    def form_valid(self, form):
        """

management/templates/management/dashboard.html
{% extends "management/base_template.html" %}
{% block content %}
<div class="row">
  <div class="card mr-2">
    <div class="card-header">
      <h6> Active Users </h6>
    </div>
    <div class="card-body">
      <table>
        {% for user in users %}
        <tr>
          <td>
            {{user}}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>

  </div>
  <div class="card">

  </div>
  <div class="card">

  </div>
</div>
{% endblock %}

management/templates/management/experiment.html
{% extends "management/base_template.html" %}
{% block content %}

<p> test</p>
{% endblock %}

management/templates/management/experiment_list.html
{% extends "management/base_template.html" %}
{% load static %}

{% block css_extra %}
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/management">Manage</a>
</li>
<li class="breadcrumb-item active">
    Experiments
</li>

{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h2>Experiments</h2>
        <div class="card">
            <div class="card-block">

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Upload Date</th>
                            <th>Scientist</th>
                            <th>Project</th>
                            <th>Tags</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                        <tr data-url="/management/fields/edit/{{field.id}}">
                            <td><input type="checkbox"></td>
                            <td>{{ item.friendly_name }}</td>
                            <td>{{ item.create_timestamp }}</td>
                            <td>{{ item.user }}</td>
                            <td>{{ item.project.name }}</td>
                            <td>{{ item.tags.all|join:", " }}</td>
                            <td>
                                <div class="btn-group" rowl="group">
                                    <a href="edit/{{item.id}}" class="btn btn-secondary">Edit</a>
                                    <a href="delete/{{item.id}}" class="btn btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td class="text-center" colspan="1000">No Experiments found</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_extra %}
{% endblock %}

management/templates/management/experiment_update.html
{% extends "management/base_template.html" %}
{% load static %}

{% block css_extra %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/css/selectize.bootstrap3.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.35.0/handsontable.full.min.css">
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/management">Manage</a>
</li>
<li class="breadcrumb-item">
    <a href="/management/experiments">Experiments</a>
</li>
<li class="breadcrumb-item active">
{{ object.friendly_name }}
</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-block">
                <h1 class="card-title">{{ object.friendly_name }}</h1>
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-warning">
                {{ error }}
                </div>
                {% endfor %}
                {% endif %}
                <form id="exp_form" method="POST">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="{{form.friendly_name.auto_id}}">
                        {{form.friendly_name.label}}</label>
                        {{form.friendly_name}}
                    </div>

                    <div class="form-group">
                        <label for="{{form.project.auto_id}}">
                        {{form.project.label}}</label>
                        {{form.project}}
                    </div>

                    <div class="form-group">
                        <label for="{{form.tags.auto_id}}">
                        {{form.tags.label}}</label>
                        {{form.tags}}
                    </div>

                    <div id="metadata_fields">
                        <legend>{{form.metadata.label}}</legend>
                        {{form.metadata}}

                        <div class="metadata_fields">
                        </div>
                    </div>

                    <input id="exp_data" name="exp_data" hidden>
                    <legend>Experiment Data </legend>
                    <div id="hot" class="form-group"></div>
                    <button class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_extra %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/standalone/selectize.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.35.0/handsontable.full.min.js"></script>
<script type="text/javascript">
    metadata_field = $("#{{ form.metadata.auto_id}}");
    var headers = {{ headers|safe }};
    var data = [
    {% for item in exp_data %}
        {{ item.experimentData|safe }},
    {% endfor %}
];
</script>

<script src="{% static 'js/exp_update.js' %}"></script>
{% endblock %}

management/templates/management/fields_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

management/templates/management/fields_list.html
{% extends "app/base_template.html" %}
{% load static %}

{% block css_extra %}
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/app">Home</a>
</li>
<li class="breadcrumb-item active">
    Fields
</li>

{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-10">
        <h1>Fields</h1>
    </div>
    <div class="col-sm-2">
        <a href="/management/fields/create" class="btn btn-secondary float-right">Add Field</a>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-block">

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Field name</th>
                            <th>Data type</th>
                            <th>Empty Value</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for field in object_list %}
                        <tr data-url="/management/fields/edit/{{field.id}}">
                            <td><input type="checkbox"></td>
                            <td>{{ field.name }}</td>
                            <td>{{ field.data_type }}</td>
                            <td>{{ field.empty }}</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a href="edit/{{ field.id }}"class="btn btn-secondary">Edit</a>
                                    <a href="delete/{{ field.id }}" class="btn btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td class="text-center" colspan="1000">No Fields found</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_extra %}
{% endblock %}

management/templates/management/groups_list.html
{% extends "management/base_template.html" %}
{% load static %}

{% block css_extra %}
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/management">Manage</a>
</li>
<li class="breadcrumb-item active">
    Groups
</li>

{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h2>User Groups</h2>
    </div>
    <div class="col">
        <a class="btn btn-primary float-right" href="create">Add Group</a>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-block">

                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Number of Users</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                        <tr data-url="/management/fields/edit/{{field.id}}">
                            <td><input type="checkbox"></td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.extra.description }}</td>
                            <td>{{ item.user_set.all.count }}</td>
                            <td>
                                <div class="btn-group" rowl="group">
                                    <a href="edit/{{item.id}}" class="btn btn-secondary">Edit</a>
                                    <a href="delete/{{item.id}}" class="btn btn-danger">Delete</a>
                                </div>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td class="text-center" colspan="1000">No Groups found</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_extra %}
{% endblock %}

management/templates/management/settings.html
{% extends "management/base_template.html" %}

{% block breadcrumb %}
{% endblock %}

{% block content %}
<div class = "card">
    <div class="card-body">
        <div class="card-block">
            <form method="post">
                <legend>Company Information</legend>
            {% csrf_token %}
		<div class = "company-data">
		{% for i in form %}
		<div class = "company-data-field">
		  <p><b>{{i.name.capitalize}}:</b><span>
		      {{i.value}}</span>
		  </p>
		</div>
		{% endfor %}
		<div class="company-data-edit" style="display: none">
		  {{form}}
		</div>
		</div>
            <legend>Settings</legend>
            {{ settings.as_p }}
            <input class="btn btn-primary" type="submit" value="Submit"/>
          </form>
        </div>
    </div>
</div>

{% endblock %}

management/templates/management/table_template.html
<table class="table table hover">
    <thead>
        <tr>
            <!-- Headers -->
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr>
            <td><input type="checkbox" name="{{ item.id }}"></td>
            <td><!-- item attribute here --></td>
            <td>
                <div class="btn-group" rowl="group">
                    <button class="btn btn-secondary">Edit</button>
                    <button class="btn btn-danger">Delete</button>
                </div>
            </td>
        </tr>

        {% empty %}
            <tr><td colspan="1000"><!-- No entries found message --></td></tr>
        {% endfor %}
    </tbody>
        }
</table>

management/templates/management/template_form.html
{% extends "app/base_template.html" %}
{% load static %}

{% block css_extra %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/css/selectize.bootstrap3.min.css">
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/management">Manage</a>
</li>
<li class="breadcrumb-item">
    <a href="/management/templates">Templates</a>
</li>
<li class="breadcrumb-item active">
    Create Template
</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-block">
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-warning">
                {{ error }}
                </div>
                {% endfor %}
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.name.auto_id }}">{{ form.name.label }}</label>
                        {{ form.name.errors }}
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.metadata.auto_id }}">{{ form.metadata.label }}</label>
                        {{ form.metadata.errors }}
                        {{ form.metadata }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.fields.auto_id }}">{{ form.fields.label }}</label>
                        {{ form.fields.errors }}
                        {{ form.fields }}
                    </div>

                    <button class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_extra %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/standalone/selectize.min.js"></script>
<script src="{% static '/js/template_form.js' %}"></script>
<script type="text/javascript">
$("#{{ form.fields.auto_id }}").selectize({
plugins: ['remove_button'],
create: CreateField
});

$("#{{ form.metadata.auto_id }}").selectize({
    plugins: ['remove_button'],
    create: CreateField
});
</script>
{% endblock %}

management/templates/management/users.html
{% extends "management/base_template.html" %}
{% block content %}

<p> test</p>
{% endblock %}