PredoxWeb/PredoxWeb/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

PredoxWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app.views import serve_image
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet

urlpatterns = [
    url(r'^devices/', FCMDeviceAuthorizedViewSet.as_view({'post':'create', 'get':'list'}), name='create_fcm_device'),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^', include('frontpage.urls')),
    url(r'^api/',include('api.urls')),
    url(r'api-token-auth/', obtain_jwt_token),
    url(r'api-token-refresh/', refresh_jwt_token),
    url(r'management/',include('management.urls')),
   # url(r'inventory/', include('inventory.urls')),
   # url(r'sop/', include('SOP.urls')),
    url(r'management/projects/', include('project_management.urls')),
    url(r'^user_images/', serve_image),
]

SOP/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', login_required(views.SOPListView.as_view())),
    url(r'^upload/$',login_required(views.SOPUploadView.as_view())),
    url(r'^download/(?P<file_id>[0-9]+)$', login_required(views.SOPDownloadView)),
    url(r'^(?P<pk>[0-9]+)$', login_required(views.SOPUpdateView.as_view())),
    url(r'^find/$', login_required(views.findSOP)),
    ]

app/models.py
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import JSONField
from accounts.models import Company
from project_management.models import Project
from PredoxWeb.settings import MEDIA_ROOT

# Create your models here.


class Tag(models.Model):
    """
    Stores tags for experiments. Stores tag name only.
    """
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (("company", "name"))


class Experiment(models.Model):
    """
    Store experiments. Does not store the data for each experiment.
    """
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    create_timestamp = models.DateTimeField(auto_now_add=True)
    edit_timestamp = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag)
    metadata = JSONField(default='')
    friendly_name = models.CharField(max_length=255)
    sop = models.ForeignKey('SOP.SOP', null=True, blank=True, on_delete = models.CASCADE)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followed_experiments", blank = True)

class ExperimentImages(models.Model):
    photo = models.ImageField(upload_to ='user_images/')
    experiment = models.ForeignKey(Experiment, on_delete = models.CASCADE)
    meta = models.CharField(max_length = 255)
    
    
class ExperimentData(models.Model):
    """
    Stores data for each experiment in JSON. The data types are validated
    using the Field data_type
    """
    company = models.ForeignKey(Company, on_delete = models.CASCADE)

    class Meta:
        verbose_name_plural = "experiment data"

    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    experimentData = JSONField()
    # More Experiment Data Here

class ExperimentDataAnnotation(models.Model):
    experimentData = models.ForeignKey(ExperimentData)
    text = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)

class Fields(models.Model):
    """
    Stores fields for adding experiments with a data type that is enforced
    on upload.
    """
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    name = models.CharField(max_length=255)

    # the data type choices
    DATA_TYPE_CHOICES = (
        ('INT', 'Integer'),
        ('FLOAT', 'Decimal'),
        ('DATE', 'Date'),
        ('STRING', 'Text'),
        )
    data_type = models.CharField(
            max_length=6,
            choices=DATA_TYPE_CHOICES,
            default='STRING'
        )
    empty = models.CharField(max_length=10, blank=True)

    class Meta:
        verbose_name_plural = "fields"
        unique_together = (("company", "name"))

    def __str__(self):
        return self.name


class Template(models.Model):
    """
    Stores templates. It is a collection of predefined fields.
    """
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    name = models.CharField(max_length=255)
    fields = models.ManyToManyField(Fields)
    metadata = models.ManyToManyField(Fields, related_name="metadata_fields")

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (("company", "name"))


class Comment(models.Model):
    """
    Stores comments on experiments.
    """
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


class UnreadNotificationManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(read=False)


class Notification(models.Model):
    """
    Model for notifications.
    Notifications are in format
    <Subject> <Predicate> <Object>
    Subject: user who performed action
    Predicate: what the action was
    Object: the watched object

    content is extra information, such as a link to the experiment uploaded or
    the comment contents.

    object_name is either Experiment.friendly_name or Project.name
    """
    PREDICATES = (
        ("COM", "commented on"),
        ("PRJ", "uploaded a new experiment to"),
        ("UPD", "updated experiment")
    )

    OBJECT_TYPES = (
        ("EXP", "experiment"),
        ("PRJ", "project"),
    )

    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="notifications", on_delete = models.CASCADE)
    subject = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="activity", on_delete = models.CASCADE)
    predicate = models.CharField(max_length=3, choices=PREDICATES)
    object_type = models.CharField(max_length=3, choices=OBJECT_TYPES)
    object_pk = models.IntegerField()
    object_name = models.CharField(max_length=255, blank=True)
    content = models.CharField(max_length=255, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    objects = models.Manager()
    unread = UnreadNotificationManager()

app/templates/app/app_header.html
<button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
    <span class="navbar-toggler-icon"></span>
</button>
<!-- <a class="navbar-brand" href="#"></a> -->
<button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">
    <span class="navbar-toggler-icon"></span>
</button>
<ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
        <a class="nav-link" href="/app">Overview</a>
    </li>
    <li class="nav-item px-3">
        <a class="nav-link" href="/app/experiments">Experiments</a>
    </li>
    <li class="nav-item px-3">
        <a class="nav-link" href="/app/projects">Projects</a>
    </li>
    <!--
    <li class="nav-item px-3">
        <a class="nav-link" href="/app/analysis">Analysis</a>
    </li>
    -->
    <li class="nav-item px-3">
        <a class="nav-link" href="/accounts/userlist">Users</a>
    </li>
</ul>
{% include 'app/app_user_menu.html' %}

app/templates/app/base_template.html
{% load static %} {% load accounts_tags %}

<!--
 * CoreUI - Open Source Bootstrap Admin Template
 * @version v1.0.6
 * @link http://coreui.io
 * Copyright (c) 2017 creativeLabs Łukasz Holeczek
 * @license MIT
 -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="">
    <title>{% block title %}Pasteur.io{% endblock %}</title>
    <!-- Main styles for this application -->
    {% block css %}
    <link href="{% static 'app/style.css' %}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'app/icons.css' %}">
    {% endblock %}


    <!-- Styles required by this views -->
    {% block css_extra %}{% endblock %}
</head>
<!-- BODY options, add following classes to body to change options

// Header options
1. '.header-fixed'                  - Fixed Header

// Brand options
1. '.brand-minimized'       - Minimized brand (Only symbol)

// Sidebar options
1. '.sidebar-fixed'                 - Fixed Sidebar
2. '.sidebar-hidden'                - Hidden Sidebar
3. '.sidebar-off-canvas'        - Off Canvas Sidebar
4. '.sidebar-minimized'         - Minimized Sidebar (Only icons)
5. '.sidebar-compact'             - Compact Sidebar

// Aside options
1. '.aside-menu-fixed'          - Fixed Aside Menu
2. '.aside-menu-hidden'         - Hidden Aside Menu
3. '.aside-menu-off-canvas' - Off Canvas Aside Menu

// Breadcrumb options
1. '.breadcrumb-fixed'          - Fixed Breadcrumb

// Footer options
1. '.footer-fixed'                  - Fixed footer

-->

<body class="app header-fixed sidebar-fixed  aside-menu-fixed sidebar-minimized aside-menu-hidden">
  <img src="{% static 'common/svg/open-iconic.min.svg' %}" class="iconic-sprite" style="display:none;" />
  <header class="app-header navbar" id="tour-header-navbar">
    {% block header %}
    {% include 'app/app_header.html' %}
    {% endblock %}
  </header>
  <div class="app-body">
    <div class="sidebar" id="tour-sidebar">
      {% block sidebar %}
      {% include 'app/app_sidebar_nav.html' %}
      {% endblock %}
    </div>
    <!-- Main content -->
    {% block main %}
    <main class="main">
      <!-- Breadcrumb -->
      <ol class="breadcrumb">
        {% block breadcrumb %}
        {% endblock %}
        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
          <div class="btn-group" role="group" aria-label="Button group">
            {% block nav_extra %}
            {% endblock %}
          </div>
        </li>
      </ol>
      <div class="container-fluid">
        <div class="animated fadeIn">
          {% block content %} {% endblock %}
        </div>
      </div>
      <!-- /.conainer-fluid -->
    </main>
    {% endblock %}
    {% block aside %}
    {% endblock %}
  </div>
  <!--     <footer class="app-footer">
	   </footer> -->
  <!-- Bootstrap and necessary plugins -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>
  <script src="{% static 'common/js/svg-injector.min.js' %}"></script>
  <script src="{% static 'common/js/hopscotch.min.js' %}"></script>
  
  <!-- CoreUI main scripts -->
  <script src="{% static 'app/js/app.js' %}"></script>
  <script src="{% static 'app/js/base.js' %}"></script>

  <!-- Plugins and scripts required by this views -->
  
  <!-- Custom scripts required by this view -->
  {% block script_extra %} {% endblock %}
</body>

{% include 'app/app_footer.html' %}
</html>

app/templates/app/create_project.html
{% extends 'app/base_template.html' %}
{% load static %}

{% block css_extra %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/app">Home</a>
</li>
<li class="breadcrumb-item">
    <a href="/app/projects">Projects</a>
</li>
<li class="breadcrumb-item active">
    Create Project

</li>
{% endblock %}

{% block content %}
{{ form.errors }}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-block">
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-warning">
                {{ error }}
                </div>
                {% endfor %}
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.name.auto_id }}">{{ form.name.label }}</label>
                        {{ form.name.errors }}
                        {{ form.name }}
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="{{ form.start.auto_id }}">{{ form.start.label }}</label>
                            {{ form.start.errors }}
                            {{ form.start }}
                        </div>

                        <div class="form-group col-md-6">
                            <label for="{{ form.end.auto_id }}">{{ form.end.label }}</label>
                            {{ form.end.errors }}
                            {{ form.end }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="{{ form.description.auto_id }}">{{ form.description.label }}</label>
                        {{ form.description.errors }}
                        {{ form.description }}
                    </div>


                    <button class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script_extra %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.4/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>

<script type="text/javascript">
    new Pikaday({ field : $("#{{ form.start.auto_id }}")[0] })
    new Pikaday({ field : $("#{{ form.end.auto_id }}")[0] })
</script>

{% endblock %}

app/templates/app/experiment.html
{% extends 'app/base_template.html' %}
{% load static %}

{% block css_extra %}
<link rel="stylesheet" type="text/css" href="{% static 'app/experiment.css' %}"/>
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/app">Home</a>
</li>
<li class="breadcrumb-item">
  <a href="/app/experiments">Experiments</a>
</li>
<li class="breadcrumb-item active">
  {% if object.friendly_name != '0'%}
    Experiment {{ object.friendly_name }}
  {% else %}
    Experiment {{ object.id}}
  {% endif %}

</li>
{% endblock %}

{% block content %}
<script "javascript">metadata = {{metadata | safe}};</script>
<div class="d-flex justify-content-end"><div class="manageButtons">
    <div class="captionedIcon">
      <svg class="icon" viewBox="0 0 8 8"><use xlink:href="#wrench"></use></svg>
      <small class="caption">Manage</small>
    </div>
    <div class="captionedIcon">
      <a data-toggle="modal" data-target="#expModal"><svg class="icon" viewBox="0 0 8 8"><use xlink:href="#trash"></use></svg>
	<small class="caption">Delete</small>
      </a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <h2 class="card-header"> Images </h2>

	<div class = "gallery">
	  <canvas id="removalChart" data-toggle="img_modal"></canvas>
	  <div class = "card-footer">
	    <div class="d-flex float-right add-photo">
	      <a data-target="#upload-modal" data-toggle="modal" class="captionedIcon">
		<svg class="icon" viewBox="0 0 8 8"><use xlink:href="#camera-slr"></use></svg>
		<small class="caption">Upload</small>
	      </a>
	    </div>
	    <div class = "row gallery-small">
	      {% for i in images %}
	      <div class="experiment-images">
		<img src=/{{i.photo}} class="img_userimg" id = "userimg_{{i.id}}" height="20em">
	      </div>
	      {% endfor %}
	    </div>
	  </div>
	
      </div>
    </div>
  </div>
  <div class = "col-md-8" id="metadatacard">
    <div class = "card">
      <h2 class = "card-header">{{object.friendly_name}} {% include 'app/watch_button.html'%}</h2>
      <div class = "card-body">
        <div class="table-responsive">
          <table class = "table table-responsive" id="metadata-table">
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class = "col-md-4"  id="commentbox">
    <div class="card">
      <h2 class="card-header">Comments</h2>
      <ul class ="list-group" id="commentList">
	{% for comment in comments %}
	<li class = "list-group-item" id="c{{ comment.pk }}">
          <div class = "media">
            <img src = "https://www.gravatar.com/avatar/e3569fea24b8a64d7b6cf0fd57234ee9?s=40" class="d-flex mr-3">
            <div class = "media-body">
              <h5 class = "mt-0">{{comment.user.first_name}} {{comment.user.last_name}}</h5>
              <div class="commentContent">
		<p>{{comment.content}}</p>
              </div>
            </div>
            <div class="d-flex justify-content-end">
              <small>{{ comment.timestamp }}</small>
            </div>
          </div>
	</li>
	{% endfor %}
      </ul>
      
      <div class="card-footer">
	<div class="form-group">
          <div class="row commentSubmit">
            {% csrf_token %}
            <textarea type="text" class="form-control col"  id="newCommentInput" rows="4" cols="50"></textarea>
	    
            <button class="btn btn-primary col-md-1" id="submitCommentButton">Submit</button>
	  </div>
	</div>
      </div>
    </div>
  </div>
  <div class="col-md-8" id="data">
    <div class="card">
      <div class="card-header">
	<h2>Raw Data
	<span class="float-right">
	  <form action="/app/experiment/csv/{{object.id}}">
	    <div class="form-group">

	      <button type="submit" class="btn btn-primary">Export</button>
	    </div>
	  </form>
	</span>
	</h2>
      </div>
      <div class="table">
	<div class="form-group">
          <table id = "experimental-data" class = "table table-hover">
	    <thead id="data-table-head">
	    </thead>
	    <tbody>
	    </tbody>
          </table>
	</div>
      </div>
    </div>
  </div>
</div>

</div>
<div class="modal fade" id="upload-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
	<h2 class="modal-title">Upload Images</h2>
	<button type="button" class = "close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	{% include "app/image_upload_form.html" %}
      </div>
    </div>
  </div>
</div>




<div class = "modal fade" id="expModal" tabindex="-1" role="dialog" aria-labelledby="expModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="titlelabel">Delete This Experiment?</h5>
        <button type="button" class = "close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> Are you Sure? This can't be undone.</p>
      </div>
      <div class="modal-footer">
        <button class = "btn" data-dismiss="modal">Don't Delete</button>
        <button class="btn btn-danger" onclick = "deleteExperiment()">Delete </button>
      </div>
    </div>
  </div>
</div>
<script>var id={{object.id}};</script>

<div class = "modal fade" id="img_modal" role="dialog" tabindex="-1" aria-labelledby="img_modal" aria-hidden="true">
  <div class="modal-dialog" id="img_modal_dialog">
    <div class="modal-body" id="img_modal_body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	<span aria-hidden="true">&times;</span>
      </button>
      <canvas id="modalCanvas"></canvas>
    </div>
  </div>
</div>




{% endblock %}



{% block script_extra %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>

  <script src = "{% static '/app/js/experiment.js' %}"></script>

  <script type="text/javascript">
    var type = 'EXP';
  </script>
  <script src='{% static "app/js/watch.js"%}'></script>
  <script src='{% static "app/js/hopscotch-tours/experimentSingle.js" %}'></script>

{% endblock %}

app/templates/app/experiment_table.html
<table class="table table-responsive-sm table-hover">
    <thead>
        <th scope="col">Name</th>
        <th scope="col">Scientist</th>
        <th scope="col">Date</th>
        <th scope="col">Project</th>
        <th scope="col">Tags</th>
    </thead>
    <tbody>
        {% for exp in data %}
        <tr class="clickable" data-id="{{exp.id}}">
            <td>{{exp.friendly_name}}</td>
            <td>{{exp.user}}</td>
            <td>{{exp.create_timestamp}}</td>
            <td>{{exp.project.name}}</td>
            <td>{{exp.tags.all|join:", "}}</td>
        </tr>
        {% empty %}
        <tr><td colspan="9999">No Experiments Found!</td></tr>
        {% endfor %}
    </tbody>
</table>

app/templates/app/experiments_page.html
{% extends 'app/base_template.html' %}
{% load static %}

{% block css_extra %}
<link type="text/css" rel="stylesheet" href="{% static 'app/jsgrid.min.css' %}" />
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
{% endblock%}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="/app">Home</a>
</li>
<li class="breadcrumb-item active">
  Experiments
</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h1>Experiments</h1>
    </div>
    <div class="col float-right">
      <button class="btn btn-secondary aside-menu-toggler float-right" style="margin: 2px;">Filter</button>
        <a class="btn btn-primary float-right" style="margin:2px;"  href="/app/upload">Upload</a>
    </div>

</div>
<div class="row">
    <div class="col">
        <div class="card" id="experiments">
            <div class="card-body">
                <div class="card-block">
                    {% with data=object_list %}
                        {% include "app/experiment_table.html" %}
                    {% endwith %}
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

{% block aside %}
<aside class="aside-menu">
    {% include 'includes/exp_filter.html' %}
</aside>
{% endblock %}

{% block script_extra %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>
<script type="text/javascript">
    $(".clickable").click(function(){
        window.location.href = "/app/experiment/" + $(this).data('id')
    });
</script>
{% endblock %}

app/templates/app/file_upload.html
<div>
    {{ form }}
</div>

app/templates/app/form_upload.html
{{ form.json }}

<div class="form-group">
    <legend>Template</legend>
    {{ form.template }}
</div>

<div class="form-group">
    <legend>Metadata</legend>
    <div id="metadata-fields">No template selected.</div>
</div>

<div class="form-group" >
    <legend>Experiment Data</legend>
    <div id="experiment-data"></div>

    <button type="button" class="btn btn-info mt-3" id="add-row">Add Row</button>
</div>

app/templates/app/image_upload_form.html
<form action = "/app/experiment/images/" method = "POST" enctype="multipart/form-data">
  {% csrf_token %}
  <p>
    <input id="exp_id"  type="hidden" name = "exp_id" value={{object.id}}>
    <input id="image" type="file" class = "" name="image">
    <input id="meta" type="text" class = "" name="meta">
  </p>
  <input type="submit" value="submit">
</form>

app/templates/app/index.html
{% extends 'app/base_template.html' %} {% load static %} {% block breadcrumb %}
<li class="breadcrumb-item active">
   Home
</li>
{% endblock %} {% block content %}
<div class="row">

    <div class="col-lg-8 pb-3 ">
        <div class="card">
          <p class="card-header"> At a Glance</p>
          {{uploads_dates}}
            <div class="card-body" id="stats">
                <p class="card-title">Nov 7-14</p>
                <hr>
                <div class="row m-1">
                    <div class="col-lg-6" id="num_exp"></div>
                    <div class="col-lg-6" id="active_users"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="pb-2 col-lg-4 pb-3">
        <div class="card">
          <p class="card-header">Tasks</p>
	  <div class = "media">
	    <div class="media-body">
	      <div id="task-graph" class="float-right media-figure">
	      </div>
	      <ul class="list-group">
		  {% include "app/task_list.html" %}
                </ul>
	      
	    </div>
	  </div>
	  
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header"><a href="/app/experiments">Latest Experiments</a></div>
            <div class="card-body">
                {% with data=latest %}
                {% include "app/experiment_table.html" %}
                {% endwith %}
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block script_extra %}
<script src="https://cdn.plot.ly/plotly-basic-latest.min.js"></script>
<script src="{% static 'app/js/index.js' %}"></script>
<script src="{% static 'app/js/hopscotch-tours/index.js' %}"></script>
<script type="text/javascript"> var show_tutorial = ("{{show_tutorial}}" == "True") </script>
{% endblock %}

app/templates/app/upload_success.html
<!-- Extends base template -->
{% extends 'app/base_template.html' %}


{% block content%}
<h1>Experiment added successfully!</h1>
<a href='/app/experiment/{{ exp_id }}'>View Experiment</a> </br>
<a href='/app/upload'>Add another experiment</a> 
{% endblock %}

app/templates/app/watch_button.html
<span class="float-right">
    <button id="watch" class="btn btn-primary {% if watched %}disabled{% endif %}">{% if watched %}Unwatch{% else %}Watch{% endif %}</button>
</span>

app/templates/app/watched_list.html
{% load accounts_tags %}
{% for n in notifications %}
<li class="list-group-item notif{{n.id}}">
    <div class="media">
        <img class="mr-3" src="{{ notification.subject.email | gravatar_url:40 }}">
        <div class="media-body">
            <a href="/accounts/user/{{ n.subject.id }}/">
                <b>{{ n.subject.get_full_name | title }}</b>
            </a>
            {{ n.get_predicate_display }}
            <a href="/app/{{ n.get_object_type_display }}/{{ n.object_pk }}/">
                <b>{{ n.object_name | title }}</b>
            </a>

            {% if n.content and not dropdown %}
            <div class="commentcontent">
                <blockquote>
                    <p>
                    {{ n.content | safe }}
                </p>
                </blockquote>
            </div>
            {% endif %}
            <div class="float-right"><small>{{ n.timestamp }}</small></div>
        </div>
        <button type="button" class="close notif_dismiss
        " aria-label="Close" data-id="{{n.id}}">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
</li>
{% empty %}
<li class="list-group-item">
No new notifications
</li>
{% endfor %}